---
exclude: "(flake.lock)"
repos:
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
        name: "Format >> End of line fixer (end-of-file-fixer)"
        priority: 1
      - id: check-added-large-files
        name: "Check  >> Added large files (check-added-large-files)"
        priority: 10
      - id: check-symlinks
        name: "Check  >> Symlinks (check-symlinks)"
        priority: 10
      - id: check-toml
        name: "Check  >> TOML files (check-toml)"
        priority: 10
      - id: check-yaml
        name: "Check  >> YAML files (check-yaml)"
        priority: 10
  - repo: local
    hooks:
      - id: typos
        name: "Check  >> Typos (typos)"
        entry: typos
        types:
          - text
        language: system
        priority: 10
  - repo: local
    hooks:
      - id: editorconfig-checker
        name: "Check  >> EditorConfig compliance (editorconfig-checker)"
        entry: ec
        types:
          - text
        language: system
        priority: 10
  - repo: local
    hooks:
      - id: shellcheck-system
        name: "Lint   >> Shell files (shellcheck-system)"
        entry: shellcheck
        types:
          - shell
        language: system
        priority: 10
  - repo: local
    hooks:
      - id: shfmt-system
        name: "Format >> Shell files (shfmt-system)"
        entry: "shfmt -w"
        types:
          - shell
        language: system
        priority: 0
  - repo: local
    hooks:
      - id: ruff-format
        name: "Format >> Python files (ruff-format)"
        entry: ruff format --force-exclude
        types:
          - python
        language: system
        priority: 0
      - id: ruff-check
        entry: ruff check --force-exclude
        args: [--fix]
        types:
          - python
        language: system
        name: "Lint   >> Python files (ruff-check)"
        priority: 10
  - repo: local
    hooks:
      - id: taplo-format
        name: "Format >> TOML files (taplo)"
        entry: "taplo format"
        types:
          - toml
        language: system
        priority: 0
