[tools]
bat = "latest"
"cargo:cargo-cache" = "latest"
"cargo:rsclip" = "latest"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "latest"
difftastic = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
rg = "latest"
sd = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
