[tools]
"cargo:bat" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:difftastic" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:hyperfine" = "latest"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "latest"
"cargo:zoxide" = "latest"
direnv = "latest"
fzf = "latest"
node = "latest"
rg = "latest"
sd = "latest"
usage = "latest"
uv = "latest"
